version = 0.1
[default]
[default.deploy]
[uat.deploy.parameters]
stack_name = "APIDiscovery-APIDiscoveryStack-uat"
s3_bucket = "starbucks-app-lambda-uat"
s3_prefix = "APIDiscovery-APIDiscoveryStack-uat"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = """
                        VPCsubnet1=\"subnet-0a8785e60207d1403\"
                        VPCsubnet2=\"subnet-0ab563e831dcce6d9\"
                        VPCsecuritygroup=\"sg-069870a195a032238\"
                        Region=\"ap-southeast-1\"
                        NodeEnv=\"development\"
                        APIStage=\"uat\"
                        FunctionName=\"APIDiscoveryFunction\"
                    """
image_repositories = []

[sit.deploy.parameters]
stack_name = "APIDiscovery-APIDiscoveryStack-sit"
s3_bucket = "starbucks-app-lambda-sit"
s3_prefix = "APIDiscovery-APIDiscoveryStack-sit"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = """
                        VPCsubnet1=\"subnet-0d8bcf91833d87308\"
                        VPCsubnet2=\"subnet-064fc90fe6af3daf2\"
                        VPCsecuritygroup=\"sg-03b65480d15f3586e\"
                        Region=\"ap-southeast-1\"
                        NodeEnv=\"development\"
                        APIStage=\"sit\"
                        FunctionName=\"APIDiscoverySITFunction\"
                    """
image_repositories = []
